    /*
    Auto-generated by: https://github.com/pmndrs/gltfjsx
    Author: DailyArt (https://sketchfab.com/D.art)
    License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
    Source: https://sketchfab.com/3d-models/robot-wont-keep-you-waiting-465323be767d4c8d91123ff2d6f6ac6f
    Title: Robot won't keep you waiting
    */

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import robotscene from '../assets/3d/link_stickman.glb'



const Robot = ({currentAnimation}) =>{
    const group = useRef();
    const { scene, animations } = useGLTF(robotscene);
    const { actions } = useAnimations(animations, group);

    useEffect(() => {
        if(currentAnimation) {
            actions['Armature.001|Armature.002|mixamo.com|Layer0'].play(); 
        } else{
            actions['Armature.001|Armature.002|mixamo.com|Layer0'].stop();}
    }, [currentAnimation]);

    return (
        <mesh ref={group} scale={[0.9,0.9,0.9]} position={[0.1,-0.8,3]}>
            <primitive object={scene}  />
        </mesh>
    );
}
export default Robot
